# Form implementation generated from reading ui file 'app2_DownYT.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from moviepy import *
from moviepy.editor import VideoFileClip
from pytube import YouTube


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(694, 292)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 0, 321, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 60, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.link_video = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.link_video.setGeometry(QtCore.QRect(190, 70, 381, 31))
        self.link_video.setObjectName("link_video")
        self.dlb = QtWidgets.QPushButton(parent=self.centralwidget)
        self.dlb.setGeometry(QtCore.QRect(310, 110, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dlb.setFont(font)
        self.dlb.setObjectName("dlb")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 694, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.dlb.clicked.connect(self.download_file)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DOWNLOAD VIDEO YOUTUBE"))
        self.label.setText(_translate("MainWindow", "YOUTUBE DOWNLOAD"))
        self.label_2.setText(_translate("MainWindow", "LINK ENTER:"))
        self.dlb.setText(_translate("MainWindow", "DOWNLOAD"))
    #xu ly
    def download_file(self):
        get_link = self.link_video.text()
        mp4 = YouTube(get_link).streams.get_highest_resolution().download()
        clip = VideoFileClip(mp4)
        clip.close()
        #cua so thong bao da tai xong
        msg = QtWidgets.QMessageBox()
        msg.setInformativeText('Video Downloaded')
        msg.exec()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
